// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: job_history.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const deleteJobHistory = `-- name: DeleteJobHistory :execrows
DELETE FROM job_histories
WHERE id = ?
`

func (q *Queries) DeleteJobHistory(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteJobHistory, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getJobHistory = `-- name: GetJobHistory :one
SELECT
  job_histories.id,
  COALESCE(job_histories.company, '') AS company,
  COALESCE(job_histories.display_name, '') AS display_name,
  job_histories.start_year,
  job_histories.start_month,
  job_histories.end_year,
  job_histories.end_month,
  job_histories.employment_type_id,
  job_employment_types.name AS employment_type,
  job_histories.project_count,
  job_histories.sort_order,
  job_histories.created_at,
  job_histories.updated_at
FROM job_histories
JOIN job_employment_types ON job_employment_types.id = job_histories.employment_type_id
WHERE job_histories.id = ?
`

type GetJobHistoryRow struct {
	ID               string
	Company          string
	DisplayName      string
	StartYear        int64
	StartMonth       int64
	EndYear          sql.NullInt64
	EndMonth         sql.NullInt64
	EmploymentTypeID string
	EmploymentType   string
	ProjectCount     int64
	SortOrder        int64
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

func (q *Queries) GetJobHistory(ctx context.Context, id string) (GetJobHistoryRow, error) {
	row := q.db.QueryRowContext(ctx, getJobHistory, id)
	var i GetJobHistoryRow
	err := row.Scan(
		&i.ID,
		&i.Company,
		&i.DisplayName,
		&i.StartYear,
		&i.StartMonth,
		&i.EndYear,
		&i.EndMonth,
		&i.EmploymentTypeID,
		&i.EmploymentType,
		&i.ProjectCount,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertJobEmploymentType = `-- name: InsertJobEmploymentType :one
INSERT INTO job_employment_types (
  id,
  name,
  sort_order
)
SELECT
  ?,
  ?,
  COALESCE(NULLIF(?, 0), COALESCE(MAX(sort_order), 0) + 1)
FROM job_employment_types
RETURNING
  id,
  name,
  sort_order,
  created_at,
  updated_at
`

type InsertJobEmploymentTypeParams struct {
	ID        string
	Name      string
	SortOrder int64
}

func (q *Queries) InsertJobEmploymentType(ctx context.Context, arg InsertJobEmploymentTypeParams) (JobEmploymentType, error) {
	row := q.db.QueryRowContext(ctx, insertJobEmploymentType, arg.ID, arg.Name, arg.SortOrder)
	var i JobEmploymentType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertJobHistory = `-- name: InsertJobHistory :one
INSERT INTO job_histories (
  company,
  display_name,
  start_year,
  start_month,
  end_year,
  end_month,
  employment_type_id,
  project_count,
  sort_order
)
SELECT
  NULLIF(?, ''),
  NULLIF(?, ''),
  ?,
  ?,
  ?,
  ?,
  ?,
  0,
  COALESCE(MIN(sort_order), 0) - 1
FROM job_histories
RETURNING
  id,
  COALESCE(company, '') AS company,
  COALESCE(display_name, '') AS display_name,
  start_year,
  start_month,
  end_year,
  end_month,
  employment_type_id,
  project_count,
  sort_order,
  created_at,
  updated_at
`

type InsertJobHistoryParams struct {
	Company          string
	DisplayName      string
	StartYear        int64
	StartMonth       int64
	EndYear          sql.NullInt64
	EndMonth         sql.NullInt64
	EmploymentTypeID string
}

func (q *Queries) InsertJobHistory(ctx context.Context, arg InsertJobHistoryParams) (JobHistory, error) {
	row := q.db.QueryRowContext(ctx, insertJobHistory,
		arg.Company,
		arg.DisplayName,
		arg.StartYear,
		arg.StartMonth,
		arg.EndYear,
		arg.EndMonth,
		arg.EmploymentTypeID,
	)
	var i JobHistory
	err := row.Scan(
		&i.ID,
		&i.Company,
		&i.DisplayName,
		&i.StartYear,
		&i.StartMonth,
		&i.EndYear,
		&i.EndMonth,
		&i.EmploymentTypeID,
		&i.ProjectCount,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listJobEmploymentTypes = `-- name: ListJobEmploymentTypes :many
SELECT
  id,
  name,
  sort_order,
  created_at,
  updated_at
FROM job_employment_types
ORDER BY sort_order ASC, name ASC
`

func (q *Queries) ListJobEmploymentTypes(ctx context.Context) ([]JobEmploymentType, error) {
	rows, err := q.db.QueryContext(ctx, listJobEmploymentTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobEmploymentType
	for rows.Next() {
		var i JobEmploymentType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobHistories = `-- name: ListJobHistories :many
SELECT
  job_histories.id,
  COALESCE(job_histories.company, '') AS company,
  COALESCE(job_histories.display_name, '') AS display_name,
  job_histories.start_year,
  job_histories.start_month,
  job_histories.end_year,
  job_histories.end_month,
  job_histories.employment_type_id,
  job_employment_types.name AS employment_type,
  job_histories.project_count,
  job_histories.sort_order,
  job_histories.created_at,
  job_histories.updated_at
FROM job_histories
JOIN job_employment_types ON job_employment_types.id = job_histories.employment_type_id
ORDER BY job_histories.sort_order ASC, job_histories.start_year DESC, job_histories.start_month DESC, COALESCE(job_histories.company, '') ASC
`

type ListJobHistoriesRow struct {
	ID               string
	Company          string
	DisplayName      string
	StartYear        int64
	StartMonth       int64
	EndYear          sql.NullInt64
	EndMonth         sql.NullInt64
	EmploymentTypeID string
	EmploymentType   string
	ProjectCount     int64
	SortOrder        int64
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

func (q *Queries) ListJobHistories(ctx context.Context) ([]ListJobHistoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listJobHistories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJobHistoriesRow
	for rows.Next() {
		var i ListJobHistoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Company,
			&i.DisplayName,
			&i.StartYear,
			&i.StartMonth,
			&i.EndYear,
			&i.EndMonth,
			&i.EmploymentTypeID,
			&i.EmploymentType,
			&i.ProjectCount,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobEmploymentType = `-- name: UpdateJobEmploymentType :one
UPDATE job_employment_types
SET
  name = ?,
  sort_order = COALESCE(NULLIF(?, 0), sort_order),
  updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING
  id,
  name,
  sort_order,
  created_at,
  updated_at
`

type UpdateJobEmploymentTypeParams struct {
	Name      string
	SortOrder int64
	ID        string
}

func (q *Queries) UpdateJobEmploymentType(ctx context.Context, arg UpdateJobEmploymentTypeParams) (JobEmploymentType, error) {
	row := q.db.QueryRowContext(ctx, updateJobEmploymentType, arg.Name, arg.SortOrder, arg.ID)
	var i JobEmploymentType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateJobHistory = `-- name: UpdateJobHistory :one
UPDATE job_histories
SET
  company = NULLIF(?, ''),
  display_name = NULLIF(?, ''),
  start_year = ?,
  start_month = ?,
  end_year = ?,
  end_month = ?,
  employment_type_id = ?,
  updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING
  id,
  COALESCE(company, '') AS company,
  COALESCE(display_name, '') AS display_name,
  start_year,
  start_month,
  end_year,
  end_month,
  employment_type_id,
  project_count,
  sort_order,
  created_at,
  updated_at
`

type UpdateJobHistoryParams struct {
	Company          string
	DisplayName      string
	StartYear        int64
	StartMonth       int64
	EndYear          sql.NullInt64
	EndMonth         sql.NullInt64
	EmploymentTypeID string
	ID               string
}

func (q *Queries) UpdateJobHistory(ctx context.Context, arg UpdateJobHistoryParams) (JobHistory, error) {
	row := q.db.QueryRowContext(ctx, updateJobHistory,
		arg.Company,
		arg.DisplayName,
		arg.StartYear,
		arg.StartMonth,
		arg.EndYear,
		arg.EndMonth,
		arg.EmploymentTypeID,
		arg.ID,
	)
	var i JobHistory
	err := row.Scan(
		&i.ID,
		&i.Company,
		&i.DisplayName,
		&i.StartYear,
		&i.StartMonth,
		&i.EndYear,
		&i.EndMonth,
		&i.EmploymentTypeID,
		&i.ProjectCount,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
