// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: job_history.sql

package db

import (
	"context"
)

const deleteJobHistory = `-- name: DeleteJobHistory :execrows
DELETE FROM job_histories
WHERE id = ?
`

func (q *Queries) DeleteJobHistory(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteJobHistory, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getJobHistory = `-- name: GetJobHistory :one
SELECT
  id,
  company,
  start_date,
  end_date,
  employment_type,
  project_count,
  sort_order,
  created_at,
  updated_at
FROM job_histories
WHERE id = ?
`

func (q *Queries) GetJobHistory(ctx context.Context, id string) (JobHistory, error) {
	row := q.db.QueryRowContext(ctx, getJobHistory, id)
	var i JobHistory
	err := row.Scan(
		&i.ID,
		&i.Company,
		&i.StartDate,
		&i.EndDate,
		&i.EmploymentType,
		&i.ProjectCount,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertJobHistory = `-- name: InsertJobHistory :one
INSERT INTO job_histories (
  id,
  company,
  start_date,
  end_date,
  employment_type,
  project_count,
  sort_order
)
SELECT
  ?,
  ?,
  ?,
  ?,
  ?,
  0,
  COALESCE(MIN(sort_order), 0) - 1
FROM job_histories
RETURNING
  id,
  company,
  start_date,
  end_date,
  employment_type,
  project_count,
  sort_order,
  created_at,
  updated_at
`

type InsertJobHistoryParams struct {
	ID             string
	Company        string
	StartDate      string
	EndDate        string
	EmploymentType string
}

func (q *Queries) InsertJobHistory(ctx context.Context, arg InsertJobHistoryParams) (JobHistory, error) {
	row := q.db.QueryRowContext(ctx, insertJobHistory,
		arg.ID,
		arg.Company,
		arg.StartDate,
		arg.EndDate,
		arg.EmploymentType,
	)
	var i JobHistory
	err := row.Scan(
		&i.ID,
		&i.Company,
		&i.StartDate,
		&i.EndDate,
		&i.EmploymentType,
		&i.ProjectCount,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listJobHistories = `-- name: ListJobHistories :many
SELECT
  id,
  company,
  start_date,
  end_date,
  employment_type,
  project_count,
  sort_order,
  created_at,
  updated_at
FROM job_histories
ORDER BY sort_order ASC, start_date DESC, company ASC
`

func (q *Queries) ListJobHistories(ctx context.Context) ([]JobHistory, error) {
	rows, err := q.db.QueryContext(ctx, listJobHistories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobHistory
	for rows.Next() {
		var i JobHistory
		if err := rows.Scan(
			&i.ID,
			&i.Company,
			&i.StartDate,
			&i.EndDate,
			&i.EmploymentType,
			&i.ProjectCount,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobHistory = `-- name: UpdateJobHistory :one
UPDATE job_histories
SET
  company = ?,
  start_date = ?,
  end_date = ?,
  employment_type = ?,
  updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING
  id,
  company,
  start_date,
  end_date,
  employment_type,
  project_count,
  sort_order,
  created_at,
  updated_at
`

type UpdateJobHistoryParams struct {
	Company        string
	StartDate      string
	EndDate        string
	EmploymentType string
	ID             string
}

func (q *Queries) UpdateJobHistory(ctx context.Context, arg UpdateJobHistoryParams) (JobHistory, error) {
	row := q.db.QueryRowContext(ctx, updateJobHistory,
		arg.Company,
		arg.StartDate,
		arg.EndDate,
		arg.EmploymentType,
		arg.ID,
	)
	var i JobHistory
	err := row.Scan(
		&i.ID,
		&i.Company,
		&i.StartDate,
		&i.EndDate,
		&i.EmploymentType,
		&i.ProjectCount,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
