// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"database/sql"
	"time"
)

type JobEmploymentType struct {
	ID        string
	Name      string
	SortOrder int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type JobHistory struct {
	ID               string
	CompanyID        string
	Company          string
	DisplayName      string
	StartYear        int64
	StartMonth       int64
	EndYear          sql.NullInt64
	EndMonth         sql.NullInt64
	EmploymentTypeID string
	ProjectCount     int64
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type Profile struct {
	ID                 string
	FamilyName         string
	GivenName          string
	Nickname           string
	AvatarUrl          string
	BirthdayYear       int64
	BirthdayMonth      int64
	BirthdayDay        int64
	Location           string
	Email              string
	Pr                 string
	Occupation         string
	EmploymentType     string
	PreferredWorkStyle string
	VisibilitySettings string
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type ProfileQualification struct {
	ID           string
	ProfileID    string
	Name         string
	AcquiredDate string
	Organization string
	Url          string
	Memo         string
	SortOrder    int64
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Project struct {
	ID           string
	Name         string
	CompanyID    string
	Company      string
	StartYear    int64
	StartMonth   int64
	EndYear      sql.NullInt64
	EndMonth     sql.NullInt64
	Description  string
	Role         string
	TeamSize     string
	Phases       string
	Achievements string
	IsDraft      int64
	SortOrder    int64
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type ProjectPhase struct {
	ID        string
	Name      string
	SortOrder int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Skill struct {
	ID            string
	SkillMasterID string
	Experience    int64
	SortOrder     int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type SkillCategory struct {
	ID        string
	Name      string
	Icon      string
	SortOrder int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type SkillMaster struct {
	ID         string
	Name       string
	CategoryID string
	Url        sql.NullString
	CreatedAt  time.Time
	UpdatedAt  time.Time
}
