// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"time"
)

type Profile struct {
	ID                 string
	UserID             string
	FullName           string
	Nickname           string
	Location           string
	Email              string
	Summary            string
	GithubUrl          string
	ZennUrl            string
	QiitaUrl           string
	WebsiteUrl         string
	PreferredWorkStyle string
	VisibilitySettings string
	CreatedAt          time.Time
	UpdatedAt          time.Time
}
