// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"database/sql"
	"time"
)

type JobEmploymentType struct {
	ID        string
	Name      string
	SortOrder int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type JobHistory struct {
	ID               string
	Company          string
	DisplayName      string
	StartYear        int64
	StartMonth       int64
	EndYear          sql.NullInt64
	EndMonth         sql.NullInt64
	EmploymentTypeID string
	ProjectCount     int64
	SortOrder        int64
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type Profile struct {
	ID                 string
	UserID             string
	FullName           string
	Nickname           string
	Location           string
	Email              string
	Summary            string
	GithubUrl          string
	ZennUrl            string
	QiitaUrl           string
	WebsiteUrl         string
	Occupation         string
	EmploymentType     string
	PreferredWorkStyle string
	VisibilitySettings string
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type ProfileQualification struct {
	ID           string
	ProfileID    string
	Name         string
	AcquiredDate string
	Organization string
	Url          string
	Memo         string
	SortOrder    int64
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Skill struct {
	ID                 string
	Name               string
	CategoryID         string
	Experience         string
	ProficiencyLevelID string
	SortOrder          int64
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type SkillCategory struct {
	ID        string
	Name      string
	Icon      string
	SortOrder int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type SkillProficiencyLevel struct {
	ID        string
	Name      string
	SortOrder int64
	CreatedAt time.Time
	UpdatedAt time.Time
}
