// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: profile.sql

package db

import (
	"context"
	"encoding/json"
	"time"
)

const getProfileByUserID = `-- name: GetProfileByUserID :one
SELECT
  id,
  user_id,
  full_name,
  nickname,
  location,
  email,
  phone,
  summary,
  github_url,
  zenn_url,
  qiita_url,
  website_url,
  preferred_work_style,
  visibility_settings,
  created_at,
  updated_at
FROM profiles
WHERE user_id = ?
LIMIT 1
`

func (q *Queries) GetProfileByUserID(ctx context.Context, userID string) (Profile, error) {
	row := q.db.QueryRowContext(ctx, getProfileByUserID, userID)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullName,
		&i.Nickname,
		&i.Location,
		&i.Email,
		&i.Phone,
		&i.Summary,
		&i.GithubUrl,
		&i.ZennUrl,
		&i.QiitaUrl,
		&i.WebsiteUrl,
		&i.PreferredWorkStyle,
		&i.VisibilitySettings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertProfile = `-- name: UpsertProfile :exec
INSERT INTO profiles (
  id,
  user_id,
  full_name,
  nickname,
  location,
  email,
  phone,
  summary,
  github_url,
  zenn_url,
  qiita_url,
  website_url,
  preferred_work_style,
  visibility_settings,
  created_at,
  updated_at
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?,
  ?, ?, ?, ?, ?, ?, ?, ?
)
ON DUPLICATE KEY UPDATE
  full_name = VALUES(full_name),
  nickname = VALUES(nickname),
  location = VALUES(location),
  email = VALUES(email),
  phone = VALUES(phone),
  summary = VALUES(summary),
  github_url = VALUES(github_url),
  zenn_url = VALUES(zenn_url),
  qiita_url = VALUES(qiita_url),
  website_url = VALUES(website_url),
  preferred_work_style = VALUES(preferred_work_style),
  visibility_settings = VALUES(visibility_settings),
  updated_at = VALUES(updated_at)
`

type UpsertProfileParams struct {
	ID                 string
	UserID             string
	FullName           string
	Nickname           string
	Location           string
	Email              string
	Phone              string
	Summary            string
	GithubUrl          string
	ZennUrl            string
	QiitaUrl           string
	WebsiteUrl         string
	PreferredWorkStyle string
	VisibilitySettings json.RawMessage
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

func (q *Queries) UpsertProfile(ctx context.Context, arg UpsertProfileParams) error {
	_, err := q.db.ExecContext(ctx, upsertProfile,
		arg.ID,
		arg.UserID,
		arg.FullName,
		arg.Nickname,
		arg.Location,
		arg.Email,
		arg.Phone,
		arg.Summary,
		arg.GithubUrl,
		arg.ZennUrl,
		arg.QiitaUrl,
		arg.WebsiteUrl,
		arg.PreferredWorkStyle,
		arg.VisibilitySettings,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
