// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: profile.sql

package db

import (
	"context"
	"time"
)

const deleteQualificationsByProfileID = `-- name: DeleteQualificationsByProfileID :exec
DELETE FROM profile_qualifications
WHERE profile_id = ?
`

func (q *Queries) DeleteQualificationsByProfileID(ctx context.Context, profileID string) error {
	_, err := q.db.ExecContext(ctx, deleteQualificationsByProfileID, profileID)
	return err
}

const getProfile = `-- name: GetProfile :one
SELECT
  id,
  family_name,
  given_name,
  nickname,
  avatar_url,
  birthday_year,
  birthday_month,
  birthday_day,
  location,
  email,
  pr,
  occupation,
  employment_type,
  preferred_work_style,
  visibility_settings,
  created_at,
  updated_at
FROM profiles
ORDER BY id ASC
LIMIT 1
`

func (q *Queries) GetProfile(ctx context.Context) (Profile, error) {
	row := q.db.QueryRowContext(ctx, getProfile)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.FamilyName,
		&i.GivenName,
		&i.Nickname,
		&i.AvatarUrl,
		&i.BirthdayYear,
		&i.BirthdayMonth,
		&i.BirthdayDay,
		&i.Location,
		&i.Email,
		&i.Pr,
		&i.Occupation,
		&i.EmploymentType,
		&i.PreferredWorkStyle,
		&i.VisibilitySettings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertQualification = `-- name: InsertQualification :exec
INSERT INTO profile_qualifications (
  id,
  profile_id,
  name,
  acquired_date,
  organization,
  url,
  memo,
  sort_order,
  created_at,
  updated_at
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type InsertQualificationParams struct {
	ID           string
	ProfileID    string
	Name         string
	AcquiredDate string
	Organization string
	Url          string
	Memo         string
	SortOrder    int64
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) InsertQualification(ctx context.Context, arg InsertQualificationParams) error {
	_, err := q.db.ExecContext(ctx, insertQualification,
		arg.ID,
		arg.ProfileID,
		arg.Name,
		arg.AcquiredDate,
		arg.Organization,
		arg.Url,
		arg.Memo,
		arg.SortOrder,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listQualificationsByProfileID = `-- name: ListQualificationsByProfileID :many
SELECT
  id,
  profile_id,
  name,
  acquired_date,
  organization,
  url,
  memo,
  sort_order,
  created_at,
  updated_at
FROM profile_qualifications
WHERE profile_id = ?
ORDER BY sort_order ASC, created_at ASC, id ASC
`

func (q *Queries) ListQualificationsByProfileID(ctx context.Context, profileID string) ([]ProfileQualification, error) {
	rows, err := q.db.QueryContext(ctx, listQualificationsByProfileID, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProfileQualification
	for rows.Next() {
		var i ProfileQualification
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.Name,
			&i.AcquiredDate,
			&i.Organization,
			&i.Url,
			&i.Memo,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProfile = `-- name: UpsertProfile :exec
INSERT INTO profiles (
  id,
  family_name,
  given_name,
  nickname,
  avatar_url,
  birthday_year,
  birthday_month,
  birthday_day,
  location,
  email,
  pr,
  occupation,
  employment_type,
  preferred_work_style,
  visibility_settings,
  created_at,
  updated_at
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?,
  ?, ?, ?, ?, ?, ?, ?, ?
)
ON CONFLICT(id) DO UPDATE SET
  family_name = excluded.family_name,
  given_name = excluded.given_name,
  nickname = excluded.nickname,
  avatar_url = excluded.avatar_url,
  birthday_year = excluded.birthday_year,
  birthday_month = excluded.birthday_month,
  birthday_day = excluded.birthday_day,
  location = excluded.location,
  email = excluded.email,
  pr = excluded.pr,
  occupation = excluded.occupation,
  employment_type = excluded.employment_type,
  preferred_work_style = excluded.preferred_work_style,
  visibility_settings = excluded.visibility_settings,
  updated_at = excluded.updated_at
`

type UpsertProfileParams struct {
	ID                 string
	FamilyName         string
	GivenName          string
	Nickname           string
	AvatarUrl          string
	BirthdayYear       int64
	BirthdayMonth      int64
	BirthdayDay        int64
	Location           string
	Email              string
	Pr                 string
	Occupation         string
	EmploymentType     string
	PreferredWorkStyle string
	VisibilitySettings string
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

func (q *Queries) UpsertProfile(ctx context.Context, arg UpsertProfileParams) error {
	_, err := q.db.ExecContext(ctx, upsertProfile,
		arg.ID,
		arg.FamilyName,
		arg.GivenName,
		arg.Nickname,
		arg.AvatarUrl,
		arg.BirthdayYear,
		arg.BirthdayMonth,
		arg.BirthdayDay,
		arg.Location,
		arg.Email,
		arg.Pr,
		arg.Occupation,
		arg.EmploymentType,
		arg.PreferredWorkStyle,
		arg.VisibilitySettings,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
