// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: project.sql

package db

import (
	"context"
	"database/sql"
)

const deleteProject = `-- name: DeleteProject :execrows
DELETE FROM projects
WHERE id = ?
`

func (q *Queries) DeleteProject(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteProject, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getProject = `-- name: GetProject :one
SELECT
  id,
  name,
  company,
  start_year,
  start_month,
  end_year,
  end_month,
  description,
  role,
  team_size,
  technologies,
  phases,
  achievements,
  is_draft,
  sort_order,
  created_at,
  updated_at
FROM projects
WHERE id = ?
`

func (q *Queries) GetProject(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Company,
		&i.StartYear,
		&i.StartMonth,
		&i.EndYear,
		&i.EndMonth,
		&i.Description,
		&i.Role,
		&i.TeamSize,
		&i.Technologies,
		&i.Phases,
		&i.Achievements,
		&i.IsDraft,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertProject = `-- name: InsertProject :one
INSERT INTO projects (
  id,
  name,
  company,
  start_year,
  start_month,
  end_year,
  end_month,
  description,
  role,
  team_size,
  technologies,
  phases,
  achievements,
  is_draft,
  sort_order
)
SELECT
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  ?,
  COALESCE(MIN(sort_order), 0) - 1
FROM projects
RETURNING
  id,
  name,
  company,
  start_year,
  start_month,
  end_year,
  end_month,
  description,
  role,
  team_size,
  technologies,
  phases,
  achievements,
  is_draft,
  sort_order,
  created_at,
  updated_at
`

type InsertProjectParams struct {
	ID           string
	Name         string
	Company      string
	StartYear    int64
	StartMonth   int64
	EndYear      sql.NullInt64
	EndMonth     sql.NullInt64
	Description  string
	Role         string
	TeamSize     string
	Technologies string
	Phases       string
	Achievements string
	IsDraft      int64
}

func (q *Queries) InsertProject(ctx context.Context, arg InsertProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, insertProject,
		arg.ID,
		arg.Name,
		arg.Company,
		arg.StartYear,
		arg.StartMonth,
		arg.EndYear,
		arg.EndMonth,
		arg.Description,
		arg.Role,
		arg.TeamSize,
		arg.Technologies,
		arg.Phases,
		arg.Achievements,
		arg.IsDraft,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Company,
		&i.StartYear,
		&i.StartMonth,
		&i.EndYear,
		&i.EndMonth,
		&i.Description,
		&i.Role,
		&i.TeamSize,
		&i.Technologies,
		&i.Phases,
		&i.Achievements,
		&i.IsDraft,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT
  id,
  name,
  company,
  start_year,
  start_month,
  end_year,
  end_month,
  description,
  role,
  team_size,
  technologies,
  phases,
  achievements,
  is_draft,
  sort_order,
  created_at,
  updated_at
FROM projects
ORDER BY sort_order ASC, start_year DESC, start_month DESC, name ASC
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Company,
			&i.StartYear,
			&i.StartMonth,
			&i.EndYear,
			&i.EndMonth,
			&i.Description,
			&i.Role,
			&i.TeamSize,
			&i.Technologies,
			&i.Phases,
			&i.Achievements,
			&i.IsDraft,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectPhases = `-- name: ListProjectPhases :many
SELECT
  id,
  name,
  sort_order,
  created_at,
  updated_at
FROM project_phases
ORDER BY sort_order ASC, name ASC
`

func (q *Queries) ListProjectPhases(ctx context.Context) ([]ProjectPhase, error) {
	rows, err := q.db.QueryContext(ctx, listProjectPhases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectPhase
	for rows.Next() {
		var i ProjectPhase
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertProjectPhase = `-- name: InsertProjectPhase :one
INSERT INTO project_phases (
  id,
  name,
  sort_order
)
SELECT
  ?,
  ?,
  COALESCE(NULLIF(?, 0), COALESCE(MAX(sort_order), 0) + 1)
FROM project_phases
RETURNING
  id,
  name,
  sort_order,
  created_at,
  updated_at
`

type InsertProjectPhaseParams struct {
	ID        string
	Name      string
	SortOrder int64
}

func (q *Queries) InsertProjectPhase(ctx context.Context, arg InsertProjectPhaseParams) (ProjectPhase, error) {
	row := q.db.QueryRowContext(ctx, insertProjectPhase, arg.ID, arg.Name, arg.SortOrder)
	var i ProjectPhase
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET
  name = ?,
  company = ?,
  start_year = ?,
  start_month = ?,
  end_year = ?,
  end_month = ?,
  description = ?,
  role = ?,
  team_size = ?,
  technologies = ?,
  phases = ?,
  achievements = ?,
  is_draft = ?,
  updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING
  id,
  name,
  company,
  start_year,
  start_month,
  end_year,
  end_month,
  description,
  role,
  team_size,
  technologies,
  phases,
  achievements,
  is_draft,
  sort_order,
  created_at,
  updated_at
`

type UpdateProjectParams struct {
	Name         string
	Company      string
	StartYear    int64
	StartMonth   int64
	EndYear      sql.NullInt64
	EndMonth     sql.NullInt64
	Description  string
	Role         string
	TeamSize     string
	Technologies string
	Phases       string
	Achievements string
	IsDraft      int64
	ID           string
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, updateProject,
		arg.Name,
		arg.Company,
		arg.StartYear,
		arg.StartMonth,
		arg.EndYear,
		arg.EndMonth,
		arg.Description,
		arg.Role,
		arg.TeamSize,
		arg.Technologies,
		arg.Phases,
		arg.Achievements,
		arg.IsDraft,
		arg.ID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Company,
		&i.StartYear,
		&i.StartMonth,
		&i.EndYear,
		&i.EndMonth,
		&i.Description,
		&i.Role,
		&i.TeamSize,
		&i.Technologies,
		&i.Phases,
		&i.Achievements,
		&i.IsDraft,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProjectPhase = `-- name: UpdateProjectPhase :one
UPDATE project_phases
SET
  name = ?,
  sort_order = COALESCE(NULLIF(?, 0), sort_order),
  updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING
  id,
  name,
  sort_order,
  created_at,
  updated_at
`

type UpdateProjectPhaseParams struct {
	Name      string
	SortOrder int64
	ID        string
}

func (q *Queries) UpdateProjectPhase(ctx context.Context, arg UpdateProjectPhaseParams) (ProjectPhase, error) {
	row := q.db.QueryRowContext(ctx, updateProjectPhase, arg.Name, arg.SortOrder, arg.ID)
	var i ProjectPhase
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
