// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: skill.sql

package db

import (
	"context"
)

const listSkillCategories = `-- name: ListSkillCategories :many
SELECT
  id,
  name,
  icon,
  sort_order,
  created_at,
  updated_at
FROM skill_categories
ORDER BY sort_order ASC, name ASC
`

func (q *Queries) ListSkillCategories(ctx context.Context) ([]SkillCategory, error) {
	rows, err := q.db.QueryContext(ctx, listSkillCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SkillCategory
	for rows.Next() {
		var i SkillCategory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkillProficiencyLevels = `-- name: ListSkillProficiencyLevels :many
SELECT
  id,
  name,
  sort_order,
  created_at,
  updated_at
FROM skill_proficiency_levels
ORDER BY sort_order ASC, name ASC
`

func (q *Queries) ListSkillProficiencyLevels(ctx context.Context) ([]SkillProficiencyLevel, error) {
	rows, err := q.db.QueryContext(ctx, listSkillProficiencyLevels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SkillProficiencyLevel
	for rows.Next() {
		var i SkillProficiencyLevel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
