// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: skill.sql

package db

import (
	"context"
	"time"
)

const deleteSkill = `-- name: DeleteSkill :execrows
DELETE FROM skills
WHERE id = ?
`

func (q *Queries) DeleteSkill(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSkill, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getSkill = `-- name: GetSkill :one
SELECT
  skills.id,
  skills.skill_master_id,
  skill_masters.name,
  skill_masters.category_id,
  skill_categories.name AS category_name,
  skills.experience,
  skills.proficiency_level_id,
  skill_proficiency_levels.name AS proficiency_name,
  skills.sort_order,
  skills.created_at,
  skills.updated_at
FROM skills
JOIN skill_masters ON skill_masters.id = skills.skill_master_id
JOIN skill_categories ON skill_categories.id = skill_masters.category_id
JOIN skill_proficiency_levels ON skill_proficiency_levels.id = skills.proficiency_level_id
WHERE skills.id = ?
`

type GetSkillRow struct {
	ID                 string
	SkillMasterID      string
	Name               string
	CategoryID         string
	CategoryName       string
	Experience         int64
	ProficiencyLevelID string
	ProficiencyName    string
	SortOrder          int64
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

func (q *Queries) GetSkill(ctx context.Context, id string) (GetSkillRow, error) {
	row := q.db.QueryRowContext(ctx, getSkill, id)
	var i GetSkillRow
	err := row.Scan(
		&i.ID,
		&i.SkillMasterID,
		&i.Name,
		&i.CategoryID,
		&i.CategoryName,
		&i.Experience,
		&i.ProficiencyLevelID,
		&i.ProficiencyName,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSkillMaster = `-- name: GetSkillMaster :one
SELECT
  skill_masters.id,
  skill_masters.name,
  skill_masters.category_id,
  skill_categories.name AS category_name,
  skill_masters.sort_order,
  skill_masters.created_at,
  skill_masters.updated_at
FROM skill_masters
JOIN skill_categories ON skill_categories.id = skill_masters.category_id
WHERE skill_masters.id = ?
`

type GetSkillMasterRow struct {
	ID           string
	Name         string
	CategoryID   string
	CategoryName string
	SortOrder    int64
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) GetSkillMaster(ctx context.Context, id string) (GetSkillMasterRow, error) {
	row := q.db.QueryRowContext(ctx, getSkillMaster, id)
	var i GetSkillMasterRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CategoryID,
		&i.CategoryName,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSkill = `-- name: InsertSkill :one
INSERT INTO skills (
  id,
  skill_master_id,
  experience,
  proficiency_level_id,
  sort_order
)
SELECT
  ?,
  ?,
  ?,
  ?,
  COALESCE(MAX(sort_order), 0) + 1
FROM skills
RETURNING
  id,
  skill_master_id,
  experience,
  proficiency_level_id,
  sort_order,
  created_at,
  updated_at
`

type InsertSkillParams struct {
	ID                 string
	SkillMasterID      string
	Experience         int64
	ProficiencyLevelID string
}

func (q *Queries) InsertSkill(ctx context.Context, arg InsertSkillParams) (Skill, error) {
	row := q.db.QueryRowContext(ctx, insertSkill,
		arg.ID,
		arg.SkillMasterID,
		arg.Experience,
		arg.ProficiencyLevelID,
	)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.SkillMasterID,
		&i.Experience,
		&i.ProficiencyLevelID,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSkillCategory = `-- name: InsertSkillCategory :one
INSERT INTO skill_categories (
  id,
  name,
  icon,
  sort_order
)
SELECT
  ?,
  ?,
  ?,
  COALESCE(MAX(sort_order), 0) + 1
FROM skill_categories
RETURNING
  id,
  name,
  icon,
  sort_order,
  created_at,
  updated_at
`

type InsertSkillCategoryParams struct {
	ID   string
	Name string
	Icon string
}

func (q *Queries) InsertSkillCategory(ctx context.Context, arg InsertSkillCategoryParams) (SkillCategory, error) {
	row := q.db.QueryRowContext(ctx, insertSkillCategory, arg.ID, arg.Name, arg.Icon)
	var i SkillCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Icon,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSkillMaster = `-- name: InsertSkillMaster :one
INSERT INTO skill_masters (
  id,
  name,
  category_id,
  sort_order
)
SELECT
  ?,
  ?,
  ?,
  COALESCE(MAX(sort_order), 0) + 1
FROM skill_masters
RETURNING
  id,
  name,
  category_id,
  sort_order,
  created_at,
  updated_at
`

type InsertSkillMasterParams struct {
	ID         string
	Name       string
	CategoryID string
}

func (q *Queries) InsertSkillMaster(ctx context.Context, arg InsertSkillMasterParams) (SkillMaster, error) {
	row := q.db.QueryRowContext(ctx, insertSkillMaster, arg.ID, arg.Name, arg.CategoryID)
	var i SkillMaster
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CategoryID,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSkillCategories = `-- name: ListSkillCategories :many
SELECT
  id,
  name,
  icon,
  sort_order,
  created_at,
  updated_at
FROM skill_categories
ORDER BY sort_order ASC, name ASC
`

func (q *Queries) ListSkillCategories(ctx context.Context) ([]SkillCategory, error) {
	rows, err := q.db.QueryContext(ctx, listSkillCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SkillCategory
	for rows.Next() {
		var i SkillCategory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkillMasters = `-- name: ListSkillMasters :many
SELECT
  skill_masters.id,
  skill_masters.name,
  skill_masters.category_id,
  skill_categories.name AS category_name,
  skill_masters.sort_order,
  skill_masters.created_at,
  skill_masters.updated_at
FROM skill_masters
JOIN skill_categories ON skill_categories.id = skill_masters.category_id
ORDER BY skill_masters.sort_order ASC, skill_masters.name ASC
`

type ListSkillMastersRow struct {
	ID           string
	Name         string
	CategoryID   string
	CategoryName string
	SortOrder    int64
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) ListSkillMasters(ctx context.Context) ([]ListSkillMastersRow, error) {
	rows, err := q.db.QueryContext(ctx, listSkillMasters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSkillMastersRow
	for rows.Next() {
		var i ListSkillMastersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CategoryID,
			&i.CategoryName,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkillProficiencyLevels = `-- name: ListSkillProficiencyLevels :many
SELECT
  id,
  name,
  sort_order,
  created_at,
  updated_at
FROM skill_proficiency_levels
ORDER BY sort_order ASC, name ASC
`

func (q *Queries) ListSkillProficiencyLevels(ctx context.Context) ([]SkillProficiencyLevel, error) {
	rows, err := q.db.QueryContext(ctx, listSkillProficiencyLevels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SkillProficiencyLevel
	for rows.Next() {
		var i SkillProficiencyLevel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkills = `-- name: ListSkills :many
SELECT
  skills.id,
  skills.skill_master_id,
  skill_masters.name,
  skill_masters.category_id,
  skill_categories.name AS category_name,
  skills.experience,
  skills.proficiency_level_id,
  skill_proficiency_levels.name AS proficiency_name,
  skills.sort_order,
  skills.created_at,
  skills.updated_at
FROM skills
JOIN skill_masters ON skill_masters.id = skills.skill_master_id
JOIN skill_categories ON skill_categories.id = skill_masters.category_id
JOIN skill_proficiency_levels ON skill_proficiency_levels.id = skills.proficiency_level_id
ORDER BY skills.sort_order ASC, skill_masters.name ASC
`

type ListSkillsRow struct {
	ID                 string
	SkillMasterID      string
	Name               string
	CategoryID         string
	CategoryName       string
	Experience         int64
	ProficiencyLevelID string
	ProficiencyName    string
	SortOrder          int64
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

func (q *Queries) ListSkills(ctx context.Context) ([]ListSkillsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSkills)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSkillsRow
	for rows.Next() {
		var i ListSkillsRow
		if err := rows.Scan(
			&i.ID,
			&i.SkillMasterID,
			&i.Name,
			&i.CategoryID,
			&i.CategoryName,
			&i.Experience,
			&i.ProficiencyLevelID,
			&i.ProficiencyName,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSkill = `-- name: UpdateSkill :one
UPDATE skills
SET
  skill_master_id = ?,
  experience = ?,
  proficiency_level_id = ?,
  updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING
  id,
  skill_master_id,
  experience,
  proficiency_level_id,
  sort_order,
  created_at,
  updated_at
`

type UpdateSkillParams struct {
	SkillMasterID      string
	Experience         int64
	ProficiencyLevelID string
	ID                 string
}

func (q *Queries) UpdateSkill(ctx context.Context, arg UpdateSkillParams) (Skill, error) {
	row := q.db.QueryRowContext(ctx, updateSkill,
		arg.SkillMasterID,
		arg.Experience,
		arg.ProficiencyLevelID,
		arg.ID,
	)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.SkillMasterID,
		&i.Experience,
		&i.ProficiencyLevelID,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSkillCategory = `-- name: UpdateSkillCategory :one
UPDATE skill_categories
SET
  name = ?,
  icon = ?,
  updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING
  id,
  name,
  icon,
  sort_order,
  created_at,
  updated_at
`

type UpdateSkillCategoryParams struct {
	Name string
	Icon string
	ID   string
}

func (q *Queries) UpdateSkillCategory(ctx context.Context, arg UpdateSkillCategoryParams) (SkillCategory, error) {
	row := q.db.QueryRowContext(ctx, updateSkillCategory, arg.Name, arg.Icon, arg.ID)
	var i SkillCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Icon,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSkillMaster = `-- name: UpdateSkillMaster :one
UPDATE skill_masters
SET
  name = ?,
  category_id = ?,
  updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING
  id,
  name,
  category_id,
  sort_order,
  created_at,
  updated_at
`

type UpdateSkillMasterParams struct {
	Name       string
	CategoryID string
	ID         string
}

func (q *Queries) UpdateSkillMaster(ctx context.Context, arg UpdateSkillMasterParams) (SkillMaster, error) {
	row := q.db.QueryRowContext(ctx, updateSkillMaster, arg.Name, arg.CategoryID, arg.ID)
	var i SkillMaster
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CategoryID,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
